### ISSUE TITLE
Plans to release Triton SparQ?

### ISSUE THREAD

**Issue by liyucheng09** [graphcore-research/llm-inference-research#1]
Nice job on the SparQ paper.

Do you have plans releasing the triton kernel if SparQ?
It's will be very helpful to the community.

**Comment by lukaribar** [comment]
Hi Yucheng,

Thanks a lot for your comment (and it was great meeting you in person at the conference!). I believe I replied over the email, but wanted to point here as well. At the moment we have the following SparQ implementations available/in the works:

* Triton implementation used for the attention microbenchmarks in the paper [here](https://github.com/graphcore-research/llm-inference-research/blob/benchmarks/src/gather_matmul.py).
* CPU implementation within llama.cpp [here](https://github.com/graphcore-research/sparq-llama.cpp).
* (in development, to be shared soon) PyTorch implementation (using `torch.compile` for fusing) within [gpt-fast](https://github.com/pytorch-labs/gpt-fast). For this, we are also looking at ways of speeding up the `topk` operation, in addition to the fused `gather-matmul` operations.

Luka
