### ISSUE TITLE
End-to-end Inference Time Benchmarking

### ISSUE THREAD

**Issue by prajwal1210** [graphcore-research/llm-inference-research#2]
Hi!

I was wondering if there is a way right now to benchmark the end-to-end inference times with SPAR-Q on a hugging-face model?
If so, what code should I be using for running faster inference with hugging face models?

**Comment by lukaribar** [comment]
Hi Prajwal,

Thanks a lot for your question, and apologies for being slow to respond.

We currently have an implementation of SparQ within llama.cpp [here](https://github.com/graphcore-research/sparq-llama.cpp), which can be used for end-to-end CPU benchmarks. In addition, we are working on a PyTorch implementation within [gpt-fast](https://github.com/pytorch-labs/gpt-fast) which we will be sharing soon.

Luka
